# Configuration for PraxiumLearning03's personal blog
theme: minima

# Site Title
title: PraxiumLearning03's personal bio

# Author Name
author: PraxiumLearning03

# Description of the site
description: This is where I share cool stuff
