# Configuration for PraxiumLearning03's personal blog
theme: minima

# Site Title
title: PraxiumLearning03's personal bio

# Author Name
author: PraxiumLearning03

# Description of the site
description: This is where I share cool stuff

# Social Media Links (optional)
social:
  x: @PraxiumLearning03
  github: https://github.com/PraxiumLearning03
  linkedin: https://linkedin.com/in/praxiumlearning03

# Optional: Add more configurations here (e.g., custom CSS, JS, or metadata)
extra:
  meta:
    keywords: "personal blog, learning, tech, army, leadership"
    og:image: "https://example.com/cover.jpg" # Replace with your image URL
